### PR TITLE
2020.9.19 OTA 배포

### PR DESCRIPTION
**Pull request by sukso96100**
- 다음 강의 표시 버그 수정

### CODE REVIEW

**Comment by sukso96100** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 1
           

Clones added
============
- src/tools/dbhelper.js  5
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/s-owl/skhu-app/pullRequest?prid=6203050&bid=20231350)

**Review by haeunsong — COMMENTED** [review]
넵

**Comment by sukso96100** [comment]
@haeunsong 이상 없으면 승인 처리 바랍니다

**Review by haeunsong — APPROVED** [review]
넵

**Pull request merged**
